<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="LAPTOP-J9THCFRO" name="TestNG.listenersExample" tests="7" failures="0" timestamp="2021-12-23T13:28:56 IST" time="2.029" errors="2">
  <testcase name="test4" time="2.018" classname="TestNG.listenersExample">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNG.listenersExample.test4() didn&#039;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNG.listenersExample.test4() didn't finish within the time-out 2000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNoExecutor(MethodInvocationHelper.java:348)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:281)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- test4 -->
  <system-out/>
  <testcase name="test5" time="0.001" classname="TestNG.listenersExample"/>
  <system-out/>
  <testcase name="test3" time="0.001" classname="TestNG.listenersExample">
    <skipped/>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase name="test5" time="0.001" classname="TestNG.listenersExample"/>
  <system-out/>
  <testcase name="test2" time="0.001" classname="TestNG.listenersExample">
    <error type="org.testng.TestException" message="
Method listenersExample.test2()[pri:0, instance:TestNG.listenersExample@42f93a98] should have thrown an exception of type class java.lang.RuntimeException">
      <![CDATA[org.testng.TestException: 
Method listenersExample.test2()[pri:0, instance:TestNG.listenersExample@42f93a98] should have thrown an exception of type class java.lang.RuntimeException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- test2 -->
  <system-out/>
  <testcase name="test1" time="0.006" classname="TestNG.listenersExample"/>
  <system-out/>
  <testcase name="test5" time="0.001" classname="TestNG.listenersExample"/>
  <system-out/>
</testsuite> <!-- TestNG.listenersExample -->
